Mensagem_Mito: "&6Mito atual: &5{mito}"
Setou_Mito: "&a[!] &7Mito setado para o player {mito}!"
Novo_Mito:
- ""
- ""
- "&5[MITO] &fTemos um novo mito no servidor!"
- "&5[MITO] &fParabéns para {mito}!"
- ""
- ""
Mito_Entrou:
- ""
- ""
- "&5[MITO] &fMito(a) {mito} acaba de entrar no servidor!"
- ""
- ""
Mito_Saiu:
- ""
- ""
- "&5[MITO] &fMito(a) {mito} acaba de sair do servidor!"
- ""
- ""
Sem_Permissao: "&c[!] &7Você não tem permissão para executar este comando!"
Uso_Correto: "&c[!] &7Utilize /setmito <player>!"
Player_Offline: "&c[!] &7Player {player} offline!"
Mito: "MrDery"
TAG: "&5[MITO]"