Config:
  Auto_Update: true
  Mundo_Terrenos: 'terrenos'
  Ativar_Terrenos: true
  Tempo_Terrenos: 60
  Mundos_Possiveis:
  - 'terrenos'
  - 'mundoteste'
  Flags_Padroes:
  - 'PVP allow'
  - 'ENDERMAN-GRIEF deny'
  - 'CREEPER-EXPLOSION deny'
  - 'MOB-SPAWNING allow'
  Preco_Bloco: 1000
  Preco_PvP: 500
  Preco_Mob: 500
  Cercar_Reto: false
  Bloco_Cercar: 'FENCE'
  Tamanho_Min: 10
  Tamanho_Max: 100
  Tamanho_Terreno_Pequeno: 20
  Tamanho_Terreno_Medio: 50
  Tamanho_Terreno_Grande: 100
  Limpar_Terreno_Ao_Deletar: true
  Permitir_Comprar_Em_Cima: false
  Schematic:
    Ativar: true
    Pequeno:
      Nome: 'pequeno.schematic'
      Tamanho: '10-30'
    Medio:
      Nome: 'medio.schematic'
      Tamanho: '31-60'
    Grande:
      Nome: 'grande.schematic'
      Tamanho: '61-100'
  Sub_Comandos:
    Comprar: 'comprar'
    Deletar: 'deletar'
    Renomear: 'renomear'
    AddAmigo: 'addamigo'
    DelAmigo: 'delamigo'
    PvP: 'pvp'
    Mobs: 'mob'
    Msg: 'msg'
    BlockCmd: 'blockcmd'
    UnBlockCmd: 'unblockcmd'
    TpArea: 'tparea'
    Lista: 'lista'
    Info: 'info'
    Vender: 'vender'
    Transferir: 'transferir'
    Limpar: 'limpar'
    VerAmigos: 'veramigos'
    Admin:
      Principal: 'admin'
      TpArea: 'tparea'
      Lista: 'lista'
  Grupos:
  
Mensagem:
  Comandos:
  - '&6Comandos dos terrenos:'
  - '&7/terreno comprar <area> <pequeno/medio/grande/tamanho> &f* &bCompre um terreno!'
  - '&7/terreno deletar <area> &f* &bDelete um terreno!'
  - '&7/terreno renomear <area> <novo nome> &f* &bRenomeie um terreno!'
  - '&7/terreno addamigo <area> <amigo> &f* &bAdicione um amigo ao seu terreno!'
  - '&7/terreno delamigo <area> <amigo> &f* &bRemova um amigo do seu terreno!'
  - '&7/terreno pvp <ativar/desativar> &f* &bAtive/desative o pvp de seu terreno!'
  - '&7/terreno mob <area> <ativar/desativar> &f* &bAtive/desative o spawn de mobs de seu terreno!'
  - '&7/terreno msg <mensagem> &f* &bAdicione uma mensagem ao seu terreno!'
  - '&7/terreno blockcmd </comando1,/comando2,/comando3...> &f* &bBloqueie um comando no seu terreno!'
  - '&7/terreno unblockcmd </comando1,/comando2,/comando3...> &f* &bLibere um comando no seu terreno!'
  - '&7/terreno tparea <area> &f* &bSe teleporte ao seu terreno!'
  - '&7/terreno lista &f* &bVeja seus terrenos neste mundo!'
  - '&7/terreno limpar &f* &bLimpe seu terreno!'
  - '&7/terreno vender <preco> &f* &bVenda seu terreno!'
  - '&7/terreno transferir <player> &f* &bTransfira seu terreno para um player!'
  - '&7/terreno info &f* &bVeja algumas informacoes do terreno que voce esta!'
  - '&7/terreno veramigos &f* &bVeja os membros desse terreno!'
  - '&7/terrenos &f* &bSeja teleportado a um local aleatorio para poder comprar um terreno!'
  Comandos_Admin:
  - '&6Comandos para admins:'
  - '&7/terreno admin tparea <player> <area> &f* &bSe teletransporte ate um terreno de um player!'
  - '&7/terreno admin lista <player> &f &bVeja as areas de um player!'
  Sem_Permissao: '&6[FTerrenos] &cVoce nao tem permissao para utilizar o comando &7/terreno {1}&c!'
  Sem_Permissao_Terrenos: '&6[FTerrenos] &cVoce nao tem permissao para utilizar o comando &7/terrenos&c!'
  Sem_Permissao_Pequeno: '&6[FTerrenos] &cVoce nao tem permissao para comprar um terreno pequeno!'
  Sem_Permissao_Medio: '&6[FTerrenos] &cVoce nao tem permissao para comprar um terreno medio!'
  Sem_Permissao_Grande: '&6[FTerrenos] &cVoce nao tem permissao para comprar um terreno grande!'
  Sem_Permissao_Personalizado: '&6[FTerrenos] &cVoce nao tem permissao para comprar um terreno personalizado!'
  Erro:
    Erro_Comprar: '&6[FTerrenos] &cUtilize /terreno comprar <area> <tamanho>!'
    Erro_Deletar: '&6[FTerrenos] &cUtilize /terreno deletar <area>!'
    Erro_Renomear: '&6[FTerrenos] &cUtilize /terreno renomear <area> <novo nome>!'
    Erro_AddAmigo: '&6[FTerrenos] &cUtilize /terreno addamigo <area> <amigo>!'
    Erro_DelAmigo: '&6[FTerrenos] &cUtilize /terreno delamigo <area> <amigo>!'
    Erro_PvP: '&6[FTerrenos] &cUtilize /terreno pvp <ativar/desativar>!'
    Erro_Mob: '&6[FTerrenos] &cUtilize /terreno mob <ativar/desativar>!'
    Erro_Msg: '&6[FTerrenos] &cUtilize /terreno msg <mensagem>!'
    Erro_Block_Cmd: '&6[FTerrenos] &cUtilize /terreno blockcmd </comando1,/comando2,/comando3...>!'
    Erro_UnBlock_Cmd: '&6[FTerrenos] &cUtilize /terreno unblockcmd </comando1,/comando2,/comando3...>!'
    Erro_TpArea: '&6[FTerrenos] &cUtilize /terreno tparea <area>!'
    Erro_Vender: '&6[FTerrenos] &cUtilize /terreno vender <preco>!'
    Erro_Transferir: '&6[FTerrenos] &cUtilize /terreno transferir <player>!'
    Erro_TpArea_Admin: '&6[FTerrenos] &cUtilize /terreno admin tparea <player> <terreno>!'
    Erro_Lista_Admin: '&6[FTerrenos] &cUtilize /terreno admin lista <player>!'
    Somente_Numeros: '&6[FTerrenos] &cInforme apenas numeros!'
    Nao_E_Par: '&6[FTerrenos] &cO tamanho do terreno tem que ser par!'
    Sem_Money_Comprar: '&6[FTerrenos] &cVoce nao tem dinheiro suficiente para comprar esse terreno!'
    Excedeu_Limite: '&6[FTerrenos] &cVoce so pode ter @limite terrenos!'
    Mundo_Desativar: '&6[FTerrenos] &cVoce nao pode comprar um terreno nesse mundo!'
    Sem_Money_PvP: '&6[FTerrenos] &cVoce nao tem dinheiro suficiente para ativar/desativar o pvp em um terreno!'
    PvP: '&6[FTerrenos] &cUtilize apenas ativar/desativar no valor do pvp!'
    Sem_Money_Mob: '&6[FTerrenos] &cVoce nao tem dinheiro suficiente para ativar/desativar o spawn de mobs em um terreno!'
    Mob: '&6[FTerrenos] &cUtilize apenas ativar/desativar no valor do spawn de mobs!'
    Sem_Terrenos: '&6[FTerrenos] &cVoce nao tem terrenos nesse mundo!'
    Sem_Terrenos_Staff: '&6[FTerrenos] &cEste player nao tem terrenos neste mundo!'
    Ja_Existe_Terreno_Com_O_Nome: '&6[FTerrenos] &cVoce ja tem um terreno com esse nome!'
    Terreno_Perto: '&6[FTerrenos] &cJa existe um terreno proximo ao seu, por favor, afaste-se!'
    Nao_E_Sua: '&6[FTerrenos] &cEsta area nao e sua!'
    Area_Nao_Encontrada: '&6[FTerrenos] &cArea @area nao encontrada!'
    Ja_Esta_Adicionado: '&6[FTerrenos] &c@amigo ja esta adicionado em seu terreno!'
    Nao_Esta_Adicionado: '&6[FTerrenos] &c@amigo nao esta adicionado em seu terreno!'
    Nao_Esta_Em_Uma_Area: '&6[FTerrenos] &cNenhuma area encontrada em seu local!'
    PvP_Ja_Ativado: '&6[FTerrenos] &cO PvP ja esta ativado em seu terreno!'
    PvP_Nao_Ativado: '&6[FTerrenos] &cO PvP nao esta ativado em seu terreno!'
    Mob_Ja_Ativado: '&6[FTerrenos] &cO spawn de mobs ja esta ativado em seu terreno!'
    Mob_Nao_Ativado: '&6[FTerrenos] &cO spawn de mobs nao esta ativado em seu terreno!'
    Ja_Esta_Sendo_Vendido: '&6[FTerrenos] &cEste terreno ja esta sendo vendido!'
    Nao_Pode_Comprar_Proprio_Terreno: '&6[FTerrenos] &cVoce nao pode comprar seu proprio terreno!'
    Tamanho_Invalido: '&6[FTerrenos] &cO tamanho do seu terreno tem que ser maior que 10 e menor que 100!'
    Mundo_Desativado: '&6[FTerrenos] &cVoce nao pode comprar terrenos neste mundo!'
    Placa_Invalida: '&6[FTerrenos] &cVoce nao pode criar este tipo de placa!'
    Tamanho_Maximo_Nome: '&6[FTerrenos] &cO nome do seu terreno nao pode ser maior que 8 caracteres!'
    Placas: '&6[FTerrenos] &cParece que ha 2 ou mais placas de venda neste terreno. Chame um admin urgentemente!'
    Nao_Pode_Se_Adicionar: '&6[FTerrenos] &cVoce nao pode se adicionar no terreno!'
    Nao_Esta_Em_Um_Terreno: '&6[FTerrenos] &cVoce nao esta em um terreno!'
    Excedeu_Limite_Transferir: '&6[FTerrenos] &cO player &7@player &cexcedeu o limite de terrenos que ele pode ter!'
    Ja_Existe_Terreno_Com_O_Nome_Transferir: '&6[FTerrenos] &cO player &7@player &cja tem um terreno com o nome &7@nome&c!'
    Player_Offline: '&6[FTerrenos] &cPlayer &7@player &coffline!'
    Transferir_Si_Mesmo: '&6[FTerrenos] &cVoce nao pode transferir um terreno para voce mesmo!'
    Comando_Ja_Adicionado: '&6[FTerrenos] &cEste comando ja esta bloqueado em seu terreno!'
    Comando_Nao_Adicionado: '&6[FTerrenos] &cEste comando nao esta bloqueado em seu terreno!'
    Sem_Comandos_Bloqueados: '&6[FTerrenos] &cNao existe nenhum comando bloqueado em seu terreno!'
    Nao_Eh_Dono: '&6[FTerrenos] &cO player &f{player} &cnao e o dono do terreno que voces esta tentando comprar!'
    Terrenos_Desativado: '&6[FTerrenos] &cEste comando esta desativado!'
    Aguarde_Terrenos: '&6[FTerrenos] &cAguarde &7{tempo} &csegundos para usar este comando novamente!'
    Terreno_Em_Cima: '&6[FTerrenos] &cVoce nao pode comprar um terreno por cima de outro terreno!'
    Terrenos: '&6[FTerrenos] &cNao foi possivel teleportar voce ate o mundo de terrenos!'
    Sem_Amigos: '&6[FTerrenos] &cNao existem membros neste terreno!'
  Sucesso:
    Limpando: '&6[FTerrenos] &cLimpando seu terreno. Aguarde!'
    Limpo: '&6[FTerrenos] &bSeu terreno foi limpo!'
    Teleportado_Mundo: '&6[FTerrenos] &bVoce foi teleportado a uma coordenada aleatoria!'
    Lista: '&6[FTerrenos] &bSeus terrenos nesse mundo (@nareas): &7@areas&b!'
    Lista_Staff: '&6[FTerrenos] &bTerrenos do player @player neste mundo (@nareas): &7@areas&b!'
    Comprou_Terreno: '&6[FTerrenos] &aVoce comprou um terreno @tamanhox@tamanho por @preco com o nome de @area!'
    Deletando: '&6[FTerrenos] &bDeletando seu terreno, aguarde!'
    Deletou: '&6[FTerrenos] &aTerreno deletado com sucesso!'
    Terreno_Renomeado: '&6[FTerrenos] &aTerreno @area renomeado com sucesso para @novonome!'
    Amigo_Adicionado: '&6[FTerrenos] &aAmigo @amigo adicionado com sucesso ao seu terreno!'
    Amigo_Removido: '&6[FTerrenos] &aAmigo @amigo removido com sucesso ao seu terreno!'
    PvP_Ativado: '&6[FTerrenos] &aPvP ativado com sucesso em seu terreno!'
    PvP_Desativar: '&6[FTerrenos] &aPvP desativado com sucesso em seu terreno!'
    Mob_Ativado: '&6[FTerrenos] &aSpawn de mobs ativado com sucesso em seu terreno!'
    Mob_Desativar: '&6[FTerrenos] &aSpawn de mobs desativado com sucesso em seu terreno!'
    Mensagem_De_Boas_Vindas: '&6[FTerrenos] &aMensagem de boas vindas definida com sucesso para "@msg"!'
    Comando_Desativado: '&6[FTerrenos] &aComando desativado com sucesso em seu terreno!'
    Comando_Ativado: '&6[FTerrenos] &aComando ativado com sucesso em seu terreno!'
    Comandos_Desativados: '&6[FTerrenos] &aComandos &7@comandos &adesativados com sucesso em seu terreno!'
    Comandos_Ativados: '&6[FTerrenos] &aComandos &7@comandos &aativados com sucesso em seu terreno!'
    Teleportado: '&6[FTerrenos] &aVoce foi teleportado com sucesso ate seu terreno!'
    Teleportado_Staff: '&6[FTerrenos] &aVoce foi teleportado ao terreno do player @player!'
    Vendendo: '&6[FTerrenos] &aTerreno colocado a venda com sucesso!'
    PvP_Desativado: '&6[FTerrenos] &aPvP desativado com sucesso!'
    PvP_Ativado: '&6[FTerrenos] &aPvP desativado com sucesso!'
    Mob_Desativado: '&6[FTerrenos] &aSpawn de mobs desativado com sucesso!'
    Mob_Ativado: '&6[FTerrenos] &aSpawn de mobs desativado com sucesso!'
    Limpou: '&6[FTerrenos] &aVoce limpou esse terreno com sucesso!'
    Comprou: '&6[FTerrenos] &aEsse terreno agora e seu!'
    Cancelou_Venda: '&6[FTerrenos] &aVenda do terreno cancelada!'
    Compraram: '&6[FTerrenos] &bO player &7@player &bacabou de comprar seu terreno!'
    Terreno_Transferido: '&6[FTerrenos] &bVoce transferiu seu terreno para o player &7@player&b!'
    Terreno_Transferido_Voce: '&6[FTerrenos] &eO player &7@player &etransferiu o terreno &7@area &epara voce!'
    Amigos: '&6[FTerrenos] &eMembros deste terreno: &f@amigos'
    Info_Area:
    - '&6Informacoes do terreno:'
    - '&7Dono: &c@dono'
    - '&7PvP: &c@pvp'
    - '&7Mobs: &c@mob'