Config:
  Key: "COLOQUE SUA KEY AQUI"

Mensagem:
  Sem_Permissao: "&c[!] &7Voce nao tem permissao para utilizar este comando!"
  Sem_Permissao_Arena: "&c[!] &7Voce nao tem permissao para entrar na arena &f@arena&7!"
  Morreu: "&3Voce morreu na arena &7@arena&3!"
  Entrou_Arena: "&6[FArenas] &b@player &3entrou na arena &f@arena&3!"
  Forma_Da_Location: "&6@id &f- &6World: &e@world &f| &6X: &e@x &f| &6Y: &e@y &f| &6Z: &e@z &f| &6Yaw: &e@Yaw &f| &6Pitch: &e@pitch"
  Comandos:
  - "&6Comandos do FArenas:"
  - "&3/arena entrar <arena> &f* &3Entre em uma arena!"
  - "&3/arena sair &f* &3Saia da arena que voce esta!"
  - "&3/arena lista &f* &3Veja as arenas disponiveis!"
  - "&3/arena criar <nome> &f* &3Crie uma arena!"
  - "&3/arena setflag <arena> <flag> <valor> &f* &3Sete um flag em uma arena!"
  - "&3/arena delflag <arena> <flag> &f* &3Delete um flag de uma arena!"
  - "&3/arena load <nome/all> &f* &3Carregue uma arena!"
  - "&3/arena reload <nome> &f* &3Recarregue uma arena (spawns, exit e flags)!"
  - "&3/arena setexit <arena> &f* &3Sete a saida de uma arena!"
  - "&3/arena addspawn <arena> &f* &3Adicione um spawn a uma arena!"
  - "&3/arena delspawn <arena> <spawn (id)> &f* &3Delete um spawn de uma arena!"
  - "&3/arena info <arena> &f* &3Veja algumas informacoes de uma arena!"
  Info:
  - "&6Informacoes da arena &e@arena&6:"
  - "&3Reducao de comando: &f@reducao"
  - "&3Permissao para poder entrar na area: &f@permissao_ativada"
  - "&3Permissao: &f@permissao"
  - "&3Comandos Liberados: &f@comandos_liberados"
  - "&3Flags da arena: &f@flags"
  - "&3Spawns da arena:"
  - "&f@spawns"
  Erro:
    Uso_Correto:
      Entrar: "&c[!] &7Utilize &f/arena entrar <arena>&7!"
      Criar: "&c[!] &7Utilize &f/arena criar <nome>&7!"
      Set_Flag: "&c[!] &7Utilize &f/arena setflag <arena> <flag> <valor>&7!"
      Del_Flag: "&c[!] &7Utilize &f/arena delflag <arena> <flag>&7!"
      Load: "&c[!] &7Utilize &f/arena load <nome/all>&7!"
      Reload: "&c[!] &7Utilize &f/arena reload <nome>&7!"
      SetExit: "&c[!] &7Utilize &f/arena setexit <arena>&7!"
      AddSpawn: "&c[!] &7Utilize &f/arena addspawn <arena>&7!"
      DelSpawn: "&c[!] &7Utilize &f/arena delspawn <arena> <spawn (id)>&7!"
      Info: "&c[!] &7Utilize &f/arena info <arena>&7!"
    Mundo_Nao_Existe: "&c[!] &7Parece que o mundo do spawn dessa arena nao existe, informe a um &c&lADM&7!"
    Arena_Nao_Existe: "&c[!] &7A arena &f@arena &7nao existe!"
    Arena_Ja_Existe: "&c[!] &7Ja existe uma arena com este nome!"
    Arena_Em_Manutencao: "&c[!] &7Esta arena esta em manutencao!"
    Arena_Lotada: "&c[!] &7Esta arena esta cheia!"
    Ja_Esta: "&c[!] &7Voce ja esta em uma arena!"
    Nao_Esta: "&c[!] &7Voce nao esta em nenhuma arena!"
    Flag_Nao_Existe: "&c[!] &7O flag informado e invalido!"
    Nao_E_Numero: "&c[!] &7Neste caso, informe apenas numeros!"
    Nao_E_Boolean: "&c[!] &7Neste caso, informe apenas &fon&7/&foff&7!"
    Comando_Bloqueado: "&c[!] &7Este comando esta bloqueado nesta arena!"
    Sem_Arenas: "&c[!] &7Nao ha nenhuma arena carregada!"
    Ja_Tem_Flag: "&c[!] &7Esta arena ja tem esse flag!"
    Nao_Tem_Flag: "&c[!] &7Esta arena nao tem esse flag!"
    Arquivo_Nao_Encontrado: "&c[!] &7Nenhum arquivo encontrado com o nome dessa arena!"
    Inventario_Vazio: "&c[!] &7Para entrar nesta arena voce precisa estar com o inventario vazio!"
    Nao_Pode_Remover: "&c[!] &7Voce nao pode remover este spawn, pois se ele for removido, esta arena nao tera spawns!"
    Nao_Tem_Spawn: "&c[!] &7Esta arena nao tem este spawn!"
  Sucesso:
    Entrou_Arena: "&b[!] &7Voce entrou na arena &f@arena&7. Boa Sorte!"
    Saiu_Arena: "&e[!] &7Voce saiu da arena &f@arena&7!"
    Criou_Arena: "&a[!] &7Voce criou a arena &f@arena&7!"
    Setou_Flag: "&a[!] &7Voce setou o flag &f@flag &7na arena &f@arena &7para &f@valor&7!"
    Flag_Deletado: "&a[!] &7Voce deletou o flag &f@flag &7da arena &f@arena&7!"
    Lista_Arenas: "&3Arenas disponiveis: &f@arenas"
    Arenas_Carregadas: "&b[!] &f@qnt &7arena(s) carregada(s)!"
    Arena_Carregada: "&a[!] &7Arena &f@arena &7carregada com sucesso!"
    Arena_Recarregada: "&a[!] &7Arena &f@arena &7recarregada!"
    Setou_Saida: "&b[!] &7Saida da arena &f@arena &7setada!"
    Adicionou_Spawn: "&b[!] &7Spawn adicionado para &f@arena&7!"
    Removeu_Spawn: "&b[!] &7Voce removeu um spawn da arena &f@arena&7!"