Blocos:
- 21
- 14
- 15
- 16
- 56
- 129
- 73
Items:
- "276;1;afiada:1;&6&lEspada Mother Fucker;&eMate com facilidade!_&aSelo de qualidade Dery!;50"
- "276;1;afiada:2;&6&lEspada Mother Fucker;&eMate com facilidade!_&aSelo de qualidade Dery!;50"
- "276;1;afiada:3;&6&lEspada Mother Fucker;&eMate com facilidade!_&aSelo de qualidade Dery!;50"
- "276;1;afiada:4;&6&lEspada Mother Fucker;&eMate com facilidade!_&aSelo de qualidade Dery!;50"
- "276;1;afiada:5;&6&lEspada Mother Fucker;&eMate com facilidade!_&aSelo de qualidade Dery!;50"
- "322:1;15;;;;100"
Chance: 100
Achou_Bau: "&6[HBau] &cVoce acaba de achar um bau da sorte!"
Nao_Pode_Abrir: "&6[HBau] &cVoce nao pode abrir o bau dos outros!"